export const KEY_MAPPING = {
  KC_A: 'A',
  KC_B: 'B',
  KC_C: 'C',
  KC_D: 'D',
  KC_E: 'E',
  KC_F: 'F',
  KC_G: 'G',
  KC_H: 'H',
  KC_I: 'I',
  KC_J: 'J',
  KC_K: 'K',
  KC_L: 'L',
  KC_M: 'M',
  KC_N: 'N',
  KC_O: 'O',
  KC_P: 'P',
  KC_Q: 'Q',
  KC_R: 'R',
  KC_S: 'S',
  KC_T: 'T',
  KC_U: 'U',
  KC_V: 'V',
  KC_W: 'W',
  KC_X: 'X',
  KC_Y: 'Y',
  KC_Z: 'Z',
  KC_0: '0',
  KC_1: '1',
  KC_2: '2',
  KC_3: '3',
  KC_4: '4',
  KC_5: '5',
  KC_6: '6',
  KC_7: '7',
  KC_8: '8',
  KC_9: '9',

  KC_F0: 'F0',
  KC_F1: 'F1',
  KC_F2: 'F2',
  KC_F3: 'F3',
  KC_F4: 'F4',
  KC_F5: 'F5',
  KC_F6: 'F6',
  KC_F7: 'F7',
  KC_F8: 'F8',
  KC_F9: 'F9',
  KC_F10: 'F10',
  KC_F11: 'F11',
  KC_F12: 'F12',
  KC_F13: 'F13',
  KC_F14: 'F14',

  KC_HOME: 'HOME',
  KC_END: 'END',
  KC_PGUP: 'Page Up',
  KC_PGDN: 'Page Down',
  KC_INS: 'Insert',
  KC_DEL: 'Delete',
  KC_PAUS: 'Pause',
  KC_SCRL: 'Scroll Lock',
  KC_PSCR: 'Screenshot',

  KC_GRV: `~\n\``,
  KC_QUOT: `"\n'`,
  KC_LBRC: `{\n[`,
  KC_RBRC: `}\n]`,
  KC_SCLN: `:\n;`,
  KC_BSLS: `|\n\\`,
  KC_COMM: `<\n,`,
  KC_DOT: `>\n.`,
  KC_SLSH: `?\n/`,

  KC_MINS: `_\n-`,
  KC_EQL: `+\n=`,

  KC_ENT: 'Enter',
  KC_ESC: 'Esc',
  KC_TAB: 'Tab',
  KC_LCTL: 'Left Ctrl',
  KC_RCTL: 'Right Crl',
  KC_LALT: 'Left Alt',
  KC_RALT: 'Right Alt',
  KC_RGUI: 'Right GUI',
  KC_LGUI: 'Left GUI',
  KC_LSFT: 'Left Shift',
  KC_RSFT: 'Right Shift',
  KC_CAPS: 'Caps Lock',
  KC_BSPC: 'Backspace',
} satisfies Record<string, string>;
